apiVersion: v1  # Use this for Service
kind: Service
metadata:
  name: fastapi-svc  # Custom name for the Service
  labels:
    app: fastapi  # Use a common label
spec:
  ports:
  - port: 8080  # Expose this port
    protocol: TCP
    nodePort: 32222  # Using
  type: NodePort     # NodePort
  selector:
    app: fastapi     # Match Pod(s) with this label